### ISSUE TITLE
"x" symbol size too big

### ISSUE THREAD

**Issue by bernstei** [lab-cosmo/chemiscope#380]
The "fixed" size "x" symbols are much bigger than squares or circles (see screenshot)

![Image](https://github.com/user-attachments/assets/2c7e877d-8d0a-4611-96f2-08895160fa2f)

**Comment by bernstei** [comment]
Other symbols are also too big, e.g. the circles in the attached screenshot (size "fixed" is selected)

![Image](https://github.com/user-attachments/assets/b1b25c87-20f6-485a-899c-f17207b2e4eb)

**Comment by ceriottm** [comment]
So, I looked a bit into this and it definitely is not a chemiscope issue. Plotly has very limited support for point shapes in 3D, there's a very stale (and closed) PR to address this here https://github.com/plotly/plotly.js/issues/4205 so it doesn't even seem worth our time to try and fix upstream. The giant X is really fugly though - I'd be inclined to only support 4 points types until a miracle happens and plotly adds better support. The larger circles are weird though, here 
![Image](https://github.com/user-attachments/assets/3397b645-09f8-4268-b6cc-667f3d8df44c)
it looks like the lozenges are biggest. 
Anyway, I'll open a PR with a couple of small fixes to actual bugs I spotted while investigating this. Since it looks like this inhomogeneous size issue irks you quite a bit, maybe you can help us determine if there is another bug I'm currently missing.

**Comment by ceriottm** [comment]
It looks like plotly actually uses glyphs from a font to draw the symbols, and it appears different browsers use different fonts, so the relative size of the symbols varies. For instance, this is the same plot as above in firefox rather than chrome ![Image](https://github.com/user-attachments/assets/830c54c1-eade-431b-8e1f-4f3d7b497011)
Ideally one should be able to select which font to use, but it doesn't look like there's documentation around this

**Comment by bernstei** [comment]
> Anyway, I'll open a PR with a couple of small fixes to actual bugs I spotted while investigating this. Since it looks like this inhomogeneous size issue irks you quite a bit, maybe you can help us determine if there is another bug I'm currently missing.

What would be useful?   A reproducing example of the large circle thing?

I definitely want more than 4 symbols, but I understand that you can't fix plotly's issues, so I could probably live with it. And the fact that it's browser dependent is _really_ ugly, but obviously not sure what you can do about that if a non-deterministic choice of fonts is what you're stuck with.

**Comment by bernstei** [comment]
I checked the file that led to the screenshot with the large circles, and I can't reproduce that behavior.  Feel free to close this issue if you want (although better control over the glyphs, or maybe just a different default set of glyphs with more sensible sizes, would be nice).  I' can always reopen, or open a new issue, if I can reproduce the size problem.

**Comment by ceriottm** [comment]
actually it was much easier than I expected to add symbols. check out #383
